
Usage: make options...

Option            Description
------            -----------
clean             Clean build directories of projects
scss              Compile SCSS files into minified CSS
gwt               Build GWT Gradle projects
j2cl              Build J2CL Maven project
build             Build both GWT and J2CL projects
run               Run the demo application
release           Create a new release from master branch
publish           Publish the latest version to Maven central

