
Usage: make options...

Option            Description
------            -----------
clean             Clean build directories of projects
scss              Compile SCSS files into minified CSS
gwt               Build GWT Gradle projects
build             Build both GWT and J2CL projects
run               Run the demo application
site              Deploy site to canvas-text.docstr.org
release           Create a new release from master branch
publish-local     Publish the latest version to Maven local
clean-s3          Clean all versions from S3
publish           Publish the latest version to Maven local and S3

